version: "3.5"

services:
  mongo:
    build:
      context: ./mongo
    container_name: "pht-mongo"
    volumes:
      - "pht-mongo-data:/data/db"
    ports:
      - 27017:27017
    environment:
      - MONGO_PHT_ADMIN_PASSWORD=admin
    networks:
      pht-net:
        aliases:
          - pht-mongo
      metadata:
        aliases:
          - pht-mongo
    restart: unless-stopped

  dind:
    image: "repository.padme-analytics.de/stationsoftware/dind:main"
    container_name: "pht-dind"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_SAN=DNS:pht-dind
    volumes:
      - "pht-dind-certs-ca:/certs/ca"
      - "pht-dind-certs-client:/certs/client"
      - "pht-dind-data:/var/lib/docker"
      - "${HOST_MOUNT_DIR-/dev/null}:${DIND_MOUNT_DIR-/dev/null}"
    networks:
      pht-net:
        aliases:
          - pht-dind
    privileged: true
    restart: unless-stopped

  pht-web:
    image: "repository.padme-analytics.de/stationsoftware/station-software:main"
    container_name: "pht-web"
    ports:
      - "3030:3030"
    volumes:
      - "pht-dind-certs-client:/usr/src/app/dind-certs-client/certs:ro"
      - "pht-vault-certs-client:/usr/src/app/vault-certs-client/certs:ro"
      - "pht-web-lockfile-vol:/lockfiledir"
    environment:
      - MONGO_HOST=pht-mongo
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_DB=pht
      - DOCKER_HOST=pht-dind
      - DOCKER_PORT=2376
      - HARBOR_ADDRESS=repository.padme-analytics.de
      - HARBOR_PORT=443
      - CENTRALSERVICE_ADDRESS=requester.padme-analytics.de
      - CENTRALSERVICE_PORT=443
      - CENTRALSERVICE_ENDPOINT=
      - AUTH_SERVER_ADDRESS=auth.padme-analytics.de
      - AUTH_SERVER_PORT=443
      - JWT_SECRET=rwthi5-pht-jwt
      - SESSION_SECRET=rwthi5-pht-session
      - VAULT_HOST=pht-vault
      - VAULT_PORT=8200
      - METADATA_PROVIDER=http://metadataprovider:9988
      - METADATA_STORE=https://metadata.padme-analytics.de
      - HOST_MOUNT_DIRECTORY=${DIND_MOUNT_DIR}
      - REACT_APP_KC_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL-https://localhost:8443}
      - KC_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL-https://localhost:8443}
      - KC_PUBLIC_KEY_URL=${KEYCLOAK_PUBLIC_KEY_URL-http://pht-keycloak:8080/realms/PHT-Station}
      - COSIGN_ENABLED=${COSIGN_ENABLED-false}
    networks:
      - pht-net
      - metadata
    depends_on:
      - mongo
      - dind
      - vault
      - pht-keycloak
    restart: unless-stopped

  vault:
    image: "repository.padme-analytics.de/stationsoftware/vault:main"
    container_name: "pht-vault"
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=https://127.0.0.1:8200
      - VAULT_API_ADDR=https://127.0.0.1:8200
      - TLS_SAN=DNS:pht-vault
    volumes:
      - pht-vault-logs:/vault/logs
      - pht-vault-data:/vault/data
      - "pht-vault-certs-ca:/certs/ca"
      - "pht-vault-certs-client:/certs/client"
    networks:
      pht-net:
        aliases:
          - pht-vault
    cap_add:
      - IPC_LOCK
    entrypoint: generate_cert.sh vault server -config=/vault/config/vault.json
    restart: unless-stopped

  telegraf:
    build:
      context: ./telegraf
    container_name: "pht-telegraf"
    networks:
      - metadata
      - pht-net
    volumes:
      - "pht-dind-certs-client:/certs:ro"
    command: bash -c "sleep 30 && telegraf"
    depends_on:
      - dind

  metadataservice:
    image: "repository.padme-analytics.de/stationsoftware/phtmetadataprovider:latest"
    container_name: "pht-metadataprovider"
    networks:
      metadata:
        aliases:
          - metadataprovider
    ports:
      - "9988:9988"
    environment:
      - MTP_UPLINK=https://metadata.padme-analytics.de/events/
      - MTP_CONFIGURATION_FOLDER=/config
    volumes:
      - "pht-metadataconfig:/config"

  postgres-keycloak:
    image: postgres:13.10
    container_name: "pht-postgres-keycloak"
    environment:
      - POSTGRES_PASSWORD=keycloak_pwd
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - "pht-postgres-keycloak-data:/var/lib/postgresql/data"
    networks:
      pht-net:
        aliases:
          - postgres-keycloak
    restart: unless-stopped

  pht-keycloak:
    build: ./keycloak
    container_name: "pht-keycloak"
    command: "start --import-realm"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD-password}
      - KC_DB_VENDOR=POSTGRES
      - KC_DB_ADDR=postgres-keycloak
      - KC_DB_DATABASE=keycloak
      - KC_DB_USER=keycloak
      - KC_DB_PASSWORD=keycloak_pwd
      - KC_HOSTNAME_URL=${KEYCLOAK_HOSTNAME_URL-https://localhost:8443}
      - KC_HOSTNAME_ADMIN_URL=${KEYCLOAK_ADMIN_URL-https://localhost:8443}
      - KC_HTTP_ENABLED=${KEYCLOAK_HTTP_ENABLED-true}
      - KC_HOSTNAME_STRICT=${KEYCLOAK_HOSTNAME_STRICT-false}
      - KC_HOSTNAME_STRICT_HTTPS=${KEYCLOAK_HOSTNAME_STRICT_HTTPS-false}
      - KC_REDIRECT_URI=${KEYCLOAK_REDIRECT_URI-http://localhost:3030/*}
    ports:
      - "8443:8443"
    depends_on:
      - postgres-keycloak
    networks:
      pht-net:
        aliases:
          - pht-keycloak
    restart: unless-stopped

networks:
  pht-net:
    external: false
    name: pht-net
  metadata:
    external: false
    name: metadata-net

volumes:
  pht-dind-certs-ca:
  pht-dind-certs-client:
  pht-dind-data:
  pht-mongo-data:
  pht-vault-logs:
  pht-vault-data:
  pht-vault-certs-ca:
  pht-vault-certs-client:
  pht-web-lockfile-vol:
  pht-metadataconfig:
  pht-postgres-keycloak-data:
