version: '3.8'

services:
  storehouse:
    image: padme-storehouse:local
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "storehouse.localhost, www.storehouse.localhost"
      VIRTUAL_PORT: 5001
      VIRTUAL_PATH: "/"
      WAPP_APPLICATION_ROOT: "/"
      API_APPLICATION_ROOT: "/storehouse/api"
      APPLICATION_HOST: "0.0.0.0"
      PORT: 5001
      ENVIRONMENT: "DEV"
      
      # Vault configuration - connect to deployed Vault (local dev mode)
      VAULT_URL: "http://host.docker.internal:8200"
      VAULT_ROLE_ID: "storehouse-role"
      VAULT_SECRET_ID: "storehouse-secret"
      VAULT_DEV_MODE: "true"
      VAULT_SKIP_VERIFY: "true"
      
      # Keycloak configuration - connect to deployed Keycloak
      KC_REALM: "pht"
      KC_URL: "http://host.docker.internal:8090"
      KC_CLIENT_ID: "storehouse"
      KC_USERINFO_URL: "http://host.docker.internal:8090/realms/pht/protocol/openid-connect/userinfo"
      
      # GitLab configuration - connect to deployed Train Depot
      GITLAB_URL: "http://host.docker.internal:8091"
      GITLAB_GROUP_ID: "5"
      GITLAB_STORE_ID: "2"
      GITLAB_FEDERATED_STORE_ID: "3"
      GITLAB_STORE_SUBFOLDER_URL: "http://host.docker.internal:8091/padme/padme-train-depot/-/tree/"
      GITLAB_FEDERATED_STORE_SUBFOLDER_URL: "http://host.docker.internal:8091/padme/padme-federated-train-depot/-/tree/"
      GITLAB_STORE_MAIN_BRANCH: "main"
      
    ports:
      - "5001:5001"
    volumes:
      # Data persistence
      - storehouse-data:/usr/src/app/api/data
      # Cache directory
      - storehouse-cache:/root/.cache
    networks:
      - padme-network

volumes:
  storehouse-data:
  storehouse-cache:

networks:
  padme-network:
    external: true
