version: "3.5"

services:
  postgres_keycloak:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - "keycloak_potgres_data:/var/lib/postgresql/data"
    networks:
      keycloaknet:
        aliases:
          - keycloak_database

  keycloak:
    build: .
    restart: unless-stopped
    command: "start --optimized"
    environment:
      VIRTUAL_HOST: "auth.${SERVICE_DOMAIN}, www.auth.${SERVICE_DOMAIN}"
      LETSENCRYPT_HOST: "auth.${SERVICE_DOMAIN}, www.auth.${SERVICE_DOMAIN}"
      VIRTUAL_PORT: 8080
      KC_DB_URL_HOST: keycloak_database
      KC_DB_URL_PORT: "5432"
      KC_DB_URL_DATABASE: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    depends_on:
      - postgres_keycloak
    networks:
      keycloaknet:
      proxynet:

volumes:
  keycloak_potgres_data:

networks:
  keycloaknet:
  proxynet:
    external: true
