services:
  dind:
    build:
      context: ./Dind
    privileged: true
    restart: unless-stopped
    ports:
      - "2376:2376"    # Docker daemon API
      - "2375:2375"    # Docker daemon API (insecure)
    volumes:
      - dind_certs:/certs
      - dind_data:/var/lib/docker
      - dind_certs_client:/certs/client
    environment:
      # Docker daemon配置（本地开发禁用TLS）
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://0.0.0.0:2375
      # 本地化配置
      DOCKER_TLS_VERIFY: ""
    networks:
      dindnet:
        aliases:
          - docker
    # 健康检查
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  dind_certs:
    name: dind-certs
  dind_data:
    name: dind-data
  dind_certs_client:
    name: dind-certs-client

networks:
  dindnet:
    name: dindnet
    driver: bridge
