/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.AdditionLink = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AdditionLink model module.
   * @module model/AdditionLink
   * @version 2.0
   */

  /**
   * Constructs a new <code>AdditionLink</code>.
   * @alias module:model/AdditionLink
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AdditionLink</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdditionLink} obj Optional instance to populate.
   * @return {module:model/AdditionLink} The populated <code>AdditionLink</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('href'))
        obj.href = ApiClient.convertToType(data['href'], 'String');
      if (data.hasOwnProperty('absolute'))
        obj.absolute = ApiClient.convertToType(data['absolute'], 'Boolean');
    }
    return obj;
  }

  /**
   * The link of the addition
   * @member {String} href
   */
  exports.prototype.href = undefined;

  /**
   * Determine whether the link is an absolute URL or not
   * @member {Boolean} absolute
   */
  exports.prototype.absolute = undefined;


  return exports;

}));
