/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.ComponentOverviewEntry = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ComponentOverviewEntry model module.
   * @module model/ComponentOverviewEntry
   * @version 2.0
   */

  /**
   * Constructs a new <code>ComponentOverviewEntry</code>.
   * @alias module:model/ComponentOverviewEntry
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ComponentOverviewEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ComponentOverviewEntry} obj Optional instance to populate.
   * @return {module:model/ComponentOverviewEntry} The populated <code>ComponentOverviewEntry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('severity'))
        obj.severity = ApiClient.convertToType(data['severity'], 'Number');
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
    }
    return obj;
  }

  /**
   * 1-None/Negligible, 2-Unknown, 3-Low, 4-Medium, 5-High
   * @member {Number} severity
   */
  exports.prototype.severity = undefined;

  /**
   * number of the components with certain severity.
   * @member {Number} count
   */
  exports.prototype.count = undefined;


  return exports;

}));
