/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.ComponentHealthStatus = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ComponentHealthStatus model module.
   * @module model/ComponentHealthStatus
   * @version 2.0
   */

  /**
   * Constructs a new <code>ComponentHealthStatus</code>.
   * The health status of component
   * @alias module:model/ComponentHealthStatus
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ComponentHealthStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ComponentHealthStatus} obj Optional instance to populate.
   * @return {module:model/ComponentHealthStatus} The populated <code>ComponentHealthStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('error'))
        obj.error = ApiClient.convertToType(data['error'], 'String');
    }
    return obj;
  }

  /**
   * The component name
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * The health status of component
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * (optional) The error message when the status is \"unhealthy\"
   * @member {String} error
   */
  exports.prototype.error = undefined;


  return exports;

}));
