/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BoolConfigItem', 'model/IntegerConfigItem', 'model/StringConfigItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BoolConfigItem'), require('./IntegerConfigItem'), require('./StringConfigItem'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.ConfigurationsResponse = factory(root.HarborApi.ApiClient, root.HarborApi.BoolConfigItem, root.HarborApi.IntegerConfigItem, root.HarborApi.StringConfigItem);
  }
}(this, function(ApiClient, BoolConfigItem, IntegerConfigItem, StringConfigItem) {
  'use strict';

  /**
   * The ConfigurationsResponse model module.
   * @module model/ConfigurationsResponse
   * @version 2.0
   */

  /**
   * Constructs a new <code>ConfigurationsResponse</code>.
   * @alias module:model/ConfigurationsResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ConfigurationsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConfigurationsResponse} obj Optional instance to populate.
   * @return {module:model/ConfigurationsResponse} The populated <code>ConfigurationsResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('auth_mode'))
        obj.authMode = StringConfigItem.constructFromObject(data['auth_mode']);
      if (data.hasOwnProperty('count_per_project'))
        obj.countPerProject = IntegerConfigItem.constructFromObject(data['count_per_project']);
      if (data.hasOwnProperty('email_from'))
        obj.emailFrom = StringConfigItem.constructFromObject(data['email_from']);
      if (data.hasOwnProperty('email_host'))
        obj.emailHost = StringConfigItem.constructFromObject(data['email_host']);
      if (data.hasOwnProperty('email_port'))
        obj.emailPort = IntegerConfigItem.constructFromObject(data['email_port']);
      if (data.hasOwnProperty('email_identity'))
        obj.emailIdentity = StringConfigItem.constructFromObject(data['email_identity']);
      if (data.hasOwnProperty('email_username'))
        obj.emailUsername = StringConfigItem.constructFromObject(data['email_username']);
      if (data.hasOwnProperty('email_ssl'))
        obj.emailSsl = BoolConfigItem.constructFromObject(data['email_ssl']);
      if (data.hasOwnProperty('email_insecure'))
        obj.emailInsecure = BoolConfigItem.constructFromObject(data['email_insecure']);
      if (data.hasOwnProperty('ldap_url'))
        obj.ldapUrl = StringConfigItem.constructFromObject(data['ldap_url']);
      if (data.hasOwnProperty('ldap_base_dn'))
        obj.ldapBaseDn = StringConfigItem.constructFromObject(data['ldap_base_dn']);
      if (data.hasOwnProperty('ldap_filter'))
        obj.ldapFilter = StringConfigItem.constructFromObject(data['ldap_filter']);
      if (data.hasOwnProperty('ldap_scope'))
        obj.ldapScope = ApiClient.convertToType(data['ldap_scope'], 'Number');
      if (data.hasOwnProperty('ldap_uid'))
        obj.ldapUid = StringConfigItem.constructFromObject(data['ldap_uid']);
      if (data.hasOwnProperty('ldap_search_dn'))
        obj.ldapSearchDn = ApiClient.convertToType(data['ldap_search_dn'], 'String');
      if (data.hasOwnProperty('ldap_timeout'))
        obj.ldapTimeout = IntegerConfigItem.constructFromObject(data['ldap_timeout']);
      if (data.hasOwnProperty('ldap_group_attribute_name'))
        obj.ldapGroupAttributeName = StringConfigItem.constructFromObject(data['ldap_group_attribute_name']);
      if (data.hasOwnProperty('ldap_group_base_dn'))
        obj.ldapGroupBaseDn = StringConfigItem.constructFromObject(data['ldap_group_base_dn']);
      if (data.hasOwnProperty('ldap_group_search_filter'))
        obj.ldapGroupSearchFilter = StringConfigItem.constructFromObject(data['ldap_group_search_filter']);
      if (data.hasOwnProperty('ldap_group_search_scope'))
        obj.ldapGroupSearchScope = IntegerConfigItem.constructFromObject(data['ldap_group_search_scope']);
      if (data.hasOwnProperty('ldap_group_admin_dn'))
        obj.ldapGroupAdminDn = StringConfigItem.constructFromObject(data['ldap_group_admin_dn']);
      if (data.hasOwnProperty('oidc_client_id'))
        obj.oidcClientId = StringConfigItem.constructFromObject(data['oidc_client_id']);
      if (data.hasOwnProperty('oidc_endpoint'))
        obj.oidcEndpoint = StringConfigItem.constructFromObject(data['oidc_endpoint']);
      if (data.hasOwnProperty('oidc_name'))
        obj.oidcName = StringConfigItem.constructFromObject(data['oidc_name']);
      if (data.hasOwnProperty('oidc_scope'))
        obj.oidcScope = StringConfigItem.constructFromObject(data['oidc_scope']);
      if (data.hasOwnProperty('oidc_verify_cert'))
        obj.oidcVerifyCert = BoolConfigItem.constructFromObject(data['oidc_verify_cert']);
      if (data.hasOwnProperty('project_creation_restriction'))
        obj.projectCreationRestriction = StringConfigItem.constructFromObject(data['project_creation_restriction']);
      if (data.hasOwnProperty('quota_per_project_enable'))
        obj.quotaPerProjectEnable = BoolConfigItem.constructFromObject(data['quota_per_project_enable']);
      if (data.hasOwnProperty('read_only'))
        obj.readOnly = BoolConfigItem.constructFromObject(data['read_only']);
      if (data.hasOwnProperty('self_registration'))
        obj.selfRegistration = BoolConfigItem.constructFromObject(data['self_registration']);
      if (data.hasOwnProperty('storage_per_project'))
        obj.storagePerProject = IntegerConfigItem.constructFromObject(data['storage_per_project']);
      if (data.hasOwnProperty('token_expiration'))
        obj.tokenExpiration = IntegerConfigItem.constructFromObject(data['token_expiration']);
      if (data.hasOwnProperty('verify_remote_cert'))
        obj.verifyRemoteCert = BoolConfigItem.constructFromObject(data['verify_remote_cert']);
      if (data.hasOwnProperty('scan_all_policy'))
        obj.scanAllPolicy = ApiClient.convertToType(data['scan_all_policy'], Object);
    }
    return obj;
  }

  /**
   * The auth mode of current system, such as \"db_auth\", \"ldap_auth\"
   * @member {module:model/StringConfigItem} authMode
   */
  exports.prototype.authMode = undefined;

  /**
   * The default count quota for the new created projects.
   * @member {module:model/IntegerConfigItem} countPerProject
   */
  exports.prototype.countPerProject = undefined;

  /**
   * The sender name for Email notification.
   * @member {module:model/StringConfigItem} emailFrom
   */
  exports.prototype.emailFrom = undefined;

  /**
   * The hostname of SMTP server that sends Email notification.
   * @member {module:model/StringConfigItem} emailHost
   */
  exports.prototype.emailHost = undefined;

  /**
   * The port of SMTP server.
   * @member {module:model/IntegerConfigItem} emailPort
   */
  exports.prototype.emailPort = undefined;

  /**
   * By default it's empty so the email_username is picked.
   * @member {module:model/StringConfigItem} emailIdentity
   */
  exports.prototype.emailIdentity = undefined;

  /**
   * The username for authenticate against SMTP server.
   * @member {module:model/StringConfigItem} emailUsername
   */
  exports.prototype.emailUsername = undefined;

  /**
   * When it's set to true the system will access Email server via TLS by default.  If it's set to false, it still will handle \"STARTTLS\" from server side.
   * @member {module:model/BoolConfigItem} emailSsl
   */
  exports.prototype.emailSsl = undefined;

  /**
   * Whether or not the certificate will be verified when Harbor tries to access the email server.
   * @member {module:model/BoolConfigItem} emailInsecure
   */
  exports.prototype.emailInsecure = undefined;

  /**
   * The URL of LDAP server.
   * @member {module:model/StringConfigItem} ldapUrl
   */
  exports.prototype.ldapUrl = undefined;

  /**
   * The Base DN for LDAP binding.
   * @member {module:model/StringConfigItem} ldapBaseDn
   */
  exports.prototype.ldapBaseDn = undefined;

  /**
   * The filter for LDAP binding.
   * @member {module:model/StringConfigItem} ldapFilter
   */
  exports.prototype.ldapFilter = undefined;

  /**
   * 0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE
   * @member {Number} ldapScope
   */
  exports.prototype.ldapScope = undefined;

  /**
   * The attribute which is used as identity for the LDAP binding, such as \"CN\" or \"SAMAccountname\"
   * @member {module:model/StringConfigItem} ldapUid
   */
  exports.prototype.ldapUid = undefined;

  /**
   * The DN of the user to do the search.
   * @member {String} ldapSearchDn
   */
  exports.prototype.ldapSearchDn = undefined;

  /**
   * timeout in seconds for connection to LDAP server.
   * @member {module:model/IntegerConfigItem} ldapTimeout
   */
  exports.prototype.ldapTimeout = undefined;

  /**
   * The attribute which is used as identity of the LDAP group, default is cn.
   * @member {module:model/StringConfigItem} ldapGroupAttributeName
   */
  exports.prototype.ldapGroupAttributeName = undefined;

  /**
   * The base DN to search LDAP group.
   * @member {module:model/StringConfigItem} ldapGroupBaseDn
   */
  exports.prototype.ldapGroupBaseDn = undefined;

  /**
   * The filter to search the ldap group.
   * @member {module:model/StringConfigItem} ldapGroupSearchFilter
   */
  exports.prototype.ldapGroupSearchFilter = undefined;

  /**
   * The scope to search ldap. '0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE'
   * @member {module:model/IntegerConfigItem} ldapGroupSearchScope
   */
  exports.prototype.ldapGroupSearchScope = undefined;

  /**
   * Specify the ldap group which have the same privilege with Harbor admin.
   * @member {module:model/StringConfigItem} ldapGroupAdminDn
   */
  exports.prototype.ldapGroupAdminDn = undefined;

  /**
   * The client id of the OIDC.
   * @member {module:model/StringConfigItem} oidcClientId
   */
  exports.prototype.oidcClientId = undefined;

  /**
   * The URL of an OIDC-complaint server, must start with 'https://'.
   * @member {module:model/StringConfigItem} oidcEndpoint
   */
  exports.prototype.oidcEndpoint = undefined;

  /**
   * The name of the OIDC provider.
   * @member {module:model/StringConfigItem} oidcName
   */
  exports.prototype.oidcName = undefined;

  /**
   * The scope sent to OIDC server during authentication, should be separated by comma. It has to contain “openid”, and “offline_access”. If you are using google, please remove “offline_access” from this field.
   * @member {module:model/StringConfigItem} oidcScope
   */
  exports.prototype.oidcScope = undefined;

  /**
   * Whether verify your OIDC server certificate, disable it if your OIDC server is hosted via self-hosted certificate.
   * @member {module:model/BoolConfigItem} oidcVerifyCert
   */
  exports.prototype.oidcVerifyCert = undefined;

  /**
   * This attribute restricts what users have the permission to create project.  It can be \"everyone\" or \"adminonly\".
   * @member {module:model/StringConfigItem} projectCreationRestriction
   */
  exports.prototype.projectCreationRestriction = undefined;

  /**
   * This attribute indicates whether quota per project enabled in harbor
   * @member {module:model/BoolConfigItem} quotaPerProjectEnable
   */
  exports.prototype.quotaPerProjectEnable = undefined;

  /**
   * 'docker push' is prohibited by Harbor if you set it to true.   
   * @member {module:model/BoolConfigItem} readOnly
   */
  exports.prototype.readOnly = undefined;

  /**
   * Whether the Harbor instance supports self-registration.  If it's set to false, admin need to add user to the instance.
   * @member {module:model/BoolConfigItem} selfRegistration
   */
  exports.prototype.selfRegistration = undefined;

  /**
   * The default storage quota for the new created projects.
   * @member {module:model/IntegerConfigItem} storagePerProject
   */
  exports.prototype.storagePerProject = undefined;

  /**
   * The expiration time of the token for internal Registry, in minutes.
   * @member {module:model/IntegerConfigItem} tokenExpiration
   */
  exports.prototype.tokenExpiration = undefined;

  /**
   * Whether or not the certificate will be verified when Harbor tries to access a remote Harbor instance for replication.
   * @member {module:model/BoolConfigItem} verifyRemoteCert
   */
  exports.prototype.verifyRemoteCert = undefined;

  /**
   * @member {Object} scanAllPolicy
   */
  exports.prototype.scanAllPolicy = undefined;


  return exports;

}));
