/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.EmailServerSetting = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The EmailServerSetting model module.
   * @module model/EmailServerSetting
   * @version 2.0
   */

  /**
   * Constructs a new <code>EmailServerSetting</code>.
   * @alias module:model/EmailServerSetting
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>EmailServerSetting</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmailServerSetting} obj Optional instance to populate.
   * @return {module:model/EmailServerSetting} The populated <code>EmailServerSetting</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('email_host'))
        obj.emailHost = ApiClient.convertToType(data['email_host'], 'String');
      if (data.hasOwnProperty('email_port'))
        obj.emailPort = ApiClient.convertToType(data['email_port'], 'Number');
      if (data.hasOwnProperty('email_username'))
        obj.emailUsername = ApiClient.convertToType(data['email_username'], 'String');
      if (data.hasOwnProperty('email_password'))
        obj.emailPassword = ApiClient.convertToType(data['email_password'], 'String');
      if (data.hasOwnProperty('email_ssl'))
        obj.emailSsl = ApiClient.convertToType(data['email_ssl'], 'Boolean');
      if (data.hasOwnProperty('email_identity'))
        obj.emailIdentity = ApiClient.convertToType(data['email_identity'], 'String');
    }
    return obj;
  }

  /**
   * The host of email server.
   * @member {String} emailHost
   */
  exports.prototype.emailHost = undefined;

  /**
   * The port of email server.
   * @member {Number} emailPort
   */
  exports.prototype.emailPort = undefined;

  /**
   * The username of email server.
   * @member {String} emailUsername
   */
  exports.prototype.emailUsername = undefined;

  /**
   * The password of email server.
   * @member {String} emailPassword
   */
  exports.prototype.emailPassword = undefined;

  /**
   * Use ssl/tls or not.
   * @member {Boolean} emailSsl
   */
  exports.prototype.emailSsl = undefined;

  /**
   * The dentity of email server.
   * @member {String} emailIdentity
   */
  exports.prototype.emailIdentity = undefined;


  return exports;

}));
