/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.FilterStyle = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The FilterStyle model module.
   * @module model/FilterStyle
   * @version 2.0
   */

  /**
   * Constructs a new <code>FilterStyle</code>.
   * The style of the resource filter
   * @alias module:model/FilterStyle
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>FilterStyle</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FilterStyle} obj Optional instance to populate.
   * @return {module:model/FilterStyle} The populated <code>FilterStyle</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('style'))
        obj.style = ApiClient.convertToType(data['style'], 'String');
      if (data.hasOwnProperty('values'))
        obj.values = ApiClient.convertToType(data['values'], ['String']);
    }
    return obj;
  }

  /**
   * The filter type
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * The filter style
   * @member {String} style
   */
  exports.prototype.style = undefined;

  /**
   * The filter values
   * @member {Array.<String>} values
   */
  exports.prototype.values = undefined;


  return exports;

}));
