/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.Icon = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Icon model module.
   * @module model/Icon
   * @version 2.0
   */

  /**
   * Constructs a new <code>Icon</code>.
   * @alias module:model/Icon
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Icon</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Icon} obj Optional instance to populate.
   * @return {module:model/Icon} The populated <code>Icon</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('content-type'))
        obj.contentType = ApiClient.convertToType(data['content-type'], 'String');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
    }
    return obj;
  }

  /**
   * The content type of the icon
   * @member {String} contentType
   */
  exports.prototype.contentType = undefined;

  /**
   * The base64 encoded content of the icon
   * @member {String} content
   */
  exports.prototype.content = undefined;


  return exports;

}));
