/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.LdapConf = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The LdapConf model module.
   * @module model/LdapConf
   * @version 2.0
   */

  /**
   * Constructs a new <code>LdapConf</code>.
   * @alias module:model/LdapConf
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>LdapConf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LdapConf} obj Optional instance to populate.
   * @return {module:model/LdapConf} The populated <code>LdapConf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ldap_url'))
        obj.ldapUrl = ApiClient.convertToType(data['ldap_url'], 'String');
      if (data.hasOwnProperty('ldap_search_dn'))
        obj.ldapSearchDn = ApiClient.convertToType(data['ldap_search_dn'], 'String');
      if (data.hasOwnProperty('ldap_search_password'))
        obj.ldapSearchPassword = ApiClient.convertToType(data['ldap_search_password'], 'String');
      if (data.hasOwnProperty('ldap_base_dn'))
        obj.ldapBaseDn = ApiClient.convertToType(data['ldap_base_dn'], 'String');
      if (data.hasOwnProperty('ldap_filter'))
        obj.ldapFilter = ApiClient.convertToType(data['ldap_filter'], 'String');
      if (data.hasOwnProperty('ldap_uid'))
        obj.ldapUid = ApiClient.convertToType(data['ldap_uid'], 'String');
      if (data.hasOwnProperty('ldap_scope'))
        obj.ldapScope = ApiClient.convertToType(data['ldap_scope'], 'Number');
      if (data.hasOwnProperty('ldap_connection_timeout'))
        obj.ldapConnectionTimeout = ApiClient.convertToType(data['ldap_connection_timeout'], 'Number');
    }
    return obj;
  }

  /**
   * The url of ldap service.
   * @member {String} ldapUrl
   */
  exports.prototype.ldapUrl = undefined;

  /**
   * The search dn of ldap service.
   * @member {String} ldapSearchDn
   */
  exports.prototype.ldapSearchDn = undefined;

  /**
   * The search password of ldap service.
   * @member {String} ldapSearchPassword
   */
  exports.prototype.ldapSearchPassword = undefined;

  /**
   * The base dn of ldap service.
   * @member {String} ldapBaseDn
   */
  exports.prototype.ldapBaseDn = undefined;

  /**
   * The serach filter of ldap service.
   * @member {String} ldapFilter
   */
  exports.prototype.ldapFilter = undefined;

  /**
   * The serach uid from ldap service attributes.
   * @member {String} ldapUid
   */
  exports.prototype.ldapUid = undefined;

  /**
   * The serach scope of ldap service.
   * @member {Number} ldapScope
   */
  exports.prototype.ldapScope = undefined;

  /**
   * The connect timeout of ldap service(second).
   * @member {Number} ldapConnectionTimeout
   */
  exports.prototype.ldapConnectionTimeout = undefined;


  return exports;

}));
