/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.LdapUsers = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The LdapUsers model module.
   * @module model/LdapUsers
   * @version 2.0
   */

  /**
   * Constructs a new <code>LdapUsers</code>.
   * @alias module:model/LdapUsers
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>LdapUsers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LdapUsers} obj Optional instance to populate.
   * @return {module:model/LdapUsers} The populated <code>LdapUsers</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ldap_username'))
        obj.ldapUsername = ApiClient.convertToType(data['ldap_username'], 'String');
      if (data.hasOwnProperty('ldap_realname'))
        obj.ldapRealname = ApiClient.convertToType(data['ldap_realname'], 'String');
      if (data.hasOwnProperty('ldap_email'))
        obj.ldapEmail = ApiClient.convertToType(data['ldap_email'], 'String');
    }
    return obj;
  }

  /**
   * search ldap user name based on ldapconf.
   * @member {String} ldapUsername
   */
  exports.prototype.ldapUsername = undefined;

  /**
   * system will try to guess the user realname form \"uid\" or \"cn\" attribute.
   * @member {String} ldapRealname
   */
  exports.prototype.ldapRealname = undefined;

  /**
   * system will try to guess the user email address form \"mail\" or \"email\" attribute.
   * @member {String} ldapEmail
   */
  exports.prototype.ldapEmail = undefined;


  return exports;

}));
