/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.Password = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Password model module.
   * @module model/Password
   * @version 2.0
   */

  /**
   * Constructs a new <code>Password</code>.
   * @alias module:model/Password
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Password</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Password} obj Optional instance to populate.
   * @return {module:model/Password} The populated <code>Password</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('old_password'))
        obj.oldPassword = ApiClient.convertToType(data['old_password'], 'String');
      if (data.hasOwnProperty('new_password'))
        obj.newPassword = ApiClient.convertToType(data['new_password'], 'String');
    }
    return obj;
  }

  /**
   * The user's existing password.
   * @member {String} oldPassword
   */
  exports.prototype.oldPassword = undefined;

  /**
   * New password for marking as to be updated.
   * @member {String} newPassword
   */
  exports.prototype.newPassword = undefined;


  return exports;

}));
