/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.Platform = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Platform model module.
   * @module model/Platform
   * @version 2.0
   */

  /**
   * Constructs a new <code>Platform</code>.
   * @alias module:model/Platform
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Platform</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Platform} obj Optional instance to populate.
   * @return {module:model/Platform} The populated <code>Platform</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('architecture'))
        obj.architecture = ApiClient.convertToType(data['architecture'], 'String');
      if (data.hasOwnProperty('os'))
        obj.os = ApiClient.convertToType(data['os'], 'String');
      if (data.hasOwnProperty('os.version'))
        obj.osVersion = ApiClient.convertToType(data['os.version'], 'String');
      if (data.hasOwnProperty('os.features'))
        obj.osFeatures = ApiClient.convertToType(data['os.features'], ['String']);
      if (data.hasOwnProperty('variant'))
        obj.variant = ApiClient.convertToType(data['variant'], 'String');
    }
    return obj;
  }

  /**
   * The architecture that the artifact applys to
   * @member {String} architecture
   */
  exports.prototype.architecture = undefined;

  /**
   * The OS that the artifact applys to
   * @member {String} os
   */
  exports.prototype.os = undefined;

  /**
   * The version of the OS that the artifact applys to
   * @member {String} osVersion
   */
  exports.prototype.osVersion = undefined;

  /**
   * The features of the OS that the artifact applys to
   * @member {Array.<String>} osFeatures
   */
  exports.prototype.osFeatures = undefined;

  /**
   * The variant of the CPU
   * @member {String} variant
   */
  exports.prototype.variant = undefined;


  return exports;

}));
