/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserEntity', 'model/UserGroup'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserEntity'), require('./UserGroup'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.ProjectMember = factory(root.HarborApi.ApiClient, root.HarborApi.UserEntity, root.HarborApi.UserGroup);
  }
}(this, function(ApiClient, UserEntity, UserGroup) {
  'use strict';

  /**
   * The ProjectMember model module.
   * @module model/ProjectMember
   * @version 2.0
   */

  /**
   * Constructs a new <code>ProjectMember</code>.
   * @alias module:model/ProjectMember
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ProjectMember</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectMember} obj Optional instance to populate.
   * @return {module:model/ProjectMember} The populated <code>ProjectMember</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('role_id'))
        obj.roleId = ApiClient.convertToType(data['role_id'], 'Number');
      if (data.hasOwnProperty('member_user'))
        obj.memberUser = UserEntity.constructFromObject(data['member_user']);
      if (data.hasOwnProperty('member_group'))
        obj.memberGroup = UserGroup.constructFromObject(data['member_group']);
    }
    return obj;
  }

  /**
   * The role id 1 for projectAdmin, 2 for developer, 3 for guest, 4 for maintainer
   * @member {Number} roleId
   */
  exports.prototype.roleId = undefined;

  /**
   * @member {module:model/UserEntity} memberUser
   */
  exports.prototype.memberUser = undefined;

  /**
   * @member {module:model/UserGroup} memberGroup
   */
  exports.prototype.memberGroup = undefined;


  return exports;

}));
