/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Registry'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Registry'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.ProjectSummary = factory(root.HarborApi.ApiClient, root.HarborApi.Registry);
  }
}(this, function(ApiClient, Registry) {
  'use strict';

  /**
   * The ProjectSummary model module.
   * @module model/ProjectSummary
   * @version 2.0
   */

  /**
   * Constructs a new <code>ProjectSummary</code>.
   * @alias module:model/ProjectSummary
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ProjectSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectSummary} obj Optional instance to populate.
   * @return {module:model/ProjectSummary} The populated <code>ProjectSummary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('repo_count'))
        obj.repoCount = ApiClient.convertToType(data['repo_count'], 'Number');
      if (data.hasOwnProperty('chart_count'))
        obj.chartCount = ApiClient.convertToType(data['chart_count'], 'Number');
      if (data.hasOwnProperty('project_admin_count'))
        obj.projectAdminCount = ApiClient.convertToType(data['project_admin_count'], 'Number');
      if (data.hasOwnProperty('maintainer_count'))
        obj.maintainerCount = ApiClient.convertToType(data['maintainer_count'], 'Number');
      if (data.hasOwnProperty('developer_count'))
        obj.developerCount = ApiClient.convertToType(data['developer_count'], 'Number');
      if (data.hasOwnProperty('guest_count'))
        obj.guestCount = ApiClient.convertToType(data['guest_count'], 'Number');
      if (data.hasOwnProperty('limited_guest_count'))
        obj.limitedGuestCount = ApiClient.convertToType(data['limited_guest_count'], 'Number');
      if (data.hasOwnProperty('quota'))
        obj.quota = ApiClient.convertToType(data['quota'], Object);
      if (data.hasOwnProperty('registry'))
        obj.registry = Registry.constructFromObject(data['registry']);
    }
    return obj;
  }

  /**
   * The number of the repositories under this project.
   * @member {Number} repoCount
   */
  exports.prototype.repoCount = undefined;

  /**
   * The total number of charts under this project.
   * @member {Number} chartCount
   */
  exports.prototype.chartCount = undefined;

  /**
   * The total number of project admin members.
   * @member {Number} projectAdminCount
   */
  exports.prototype.projectAdminCount = undefined;

  /**
   * The total number of maintainer members.
   * @member {Number} maintainerCount
   */
  exports.prototype.maintainerCount = undefined;

  /**
   * The total number of developer members.
   * @member {Number} developerCount
   */
  exports.prototype.developerCount = undefined;

  /**
   * The total number of guest members.
   * @member {Number} guestCount
   */
  exports.prototype.guestCount = undefined;

  /**
   * The total number of limited guest members.
   * @member {Number} limitedGuestCount
   */
  exports.prototype.limitedGuestCount = undefined;

  /**
   * @member {Object} quota
   */
  exports.prototype.quota = undefined;

  /**
   * @member {module:model/Registry} registry
   */
  exports.prototype.registry = undefined;


  return exports;

}));
