/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResourceList'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ResourceList'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.QuotaUpdateReq = factory(root.HarborApi.ApiClient, root.HarborApi.ResourceList);
  }
}(this, function(ApiClient, ResourceList) {
  'use strict';

  /**
   * The QuotaUpdateReq model module.
   * @module model/QuotaUpdateReq
   * @version 2.0
   */

  /**
   * Constructs a new <code>QuotaUpdateReq</code>.
   * @alias module:model/QuotaUpdateReq
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>QuotaUpdateReq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuotaUpdateReq} obj Optional instance to populate.
   * @return {module:model/QuotaUpdateReq} The populated <code>QuotaUpdateReq</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('hard'))
        obj.hard = ResourceList.constructFromObject(data['hard']);
    }
    return obj;
  }

  /**
   * The new hard limits for the quota
   * @member {module:model/ResourceList} hard
   */
  exports.prototype.hard = undefined;


  return exports;

}));
