/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Annotations', 'model/Platform'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Annotations'), require('./Platform'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.Reference = factory(root.HarborApi.ApiClient, root.HarborApi.Annotations, root.HarborApi.Platform);
  }
}(this, function(ApiClient, Annotations, Platform) {
  'use strict';

  /**
   * The Reference model module.
   * @module model/Reference
   * @version 2.0
   */

  /**
   * Constructs a new <code>Reference</code>.
   * @alias module:model/Reference
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Reference</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Reference} obj Optional instance to populate.
   * @return {module:model/Reference} The populated <code>Reference</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('parent_id'))
        obj.parentId = ApiClient.convertToType(data['parent_id'], 'Number');
      if (data.hasOwnProperty('child_id'))
        obj.childId = ApiClient.convertToType(data['child_id'], 'Number');
      if (data.hasOwnProperty('child_digest'))
        obj.childDigest = ApiClient.convertToType(data['child_digest'], 'String');
      if (data.hasOwnProperty('platform'))
        obj.platform = Platform.constructFromObject(data['platform']);
      if (data.hasOwnProperty('annotations'))
        obj.annotations = Annotations.constructFromObject(data['annotations']);
      if (data.hasOwnProperty('urls'))
        obj.urls = ApiClient.convertToType(data['urls'], ['String']);
    }
    return obj;
  }

  /**
   * The parent ID of the reference
   * @member {Number} parentId
   */
  exports.prototype.parentId = undefined;

  /**
   * The child ID of the reference
   * @member {Number} childId
   */
  exports.prototype.childId = undefined;

  /**
   * The digest of the child artifact
   * @member {String} childDigest
   */
  exports.prototype.childDigest = undefined;

  /**
   * @member {module:model/Platform} platform
   */
  exports.prototype.platform = undefined;

  /**
   * @member {module:model/Annotations} annotations
   */
  exports.prototype.annotations = undefined;

  /**
   * The download URLs
   * @member {Array.<String>} urls
   */
  exports.prototype.urls = undefined;


  return exports;

}));
