/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Registry', 'model/ReplicationFilter', 'model/ReplicationTrigger'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Registry'), require('./ReplicationFilter'), require('./ReplicationTrigger'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.ReplicationPolicy = factory(root.HarborApi.ApiClient, root.HarborApi.Registry, root.HarborApi.ReplicationFilter, root.HarborApi.ReplicationTrigger);
  }
}(this, function(ApiClient, Registry, ReplicationFilter, ReplicationTrigger) {
  'use strict';

  /**
   * The ReplicationPolicy model module.
   * @module model/ReplicationPolicy
   * @version 2.0
   */

  /**
   * Constructs a new <code>ReplicationPolicy</code>.
   * @alias module:model/ReplicationPolicy
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ReplicationPolicy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReplicationPolicy} obj Optional instance to populate.
   * @return {module:model/ReplicationPolicy} The populated <code>ReplicationPolicy</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('src_registry'))
        obj.srcRegistry = Registry.constructFromObject(data['src_registry']);
      if (data.hasOwnProperty('dest_registry'))
        obj.destRegistry = Registry.constructFromObject(data['dest_registry']);
      if (data.hasOwnProperty('dest_namespace'))
        obj.destNamespace = ApiClient.convertToType(data['dest_namespace'], 'String');
      if (data.hasOwnProperty('trigger'))
        obj.trigger = ReplicationTrigger.constructFromObject(data['trigger']);
      if (data.hasOwnProperty('filters'))
        obj.filters = ApiClient.convertToType(data['filters'], [ReplicationFilter]);
      if (data.hasOwnProperty('deletion'))
        obj.deletion = ApiClient.convertToType(data['deletion'], 'Boolean');
      if (data.hasOwnProperty('override'))
        obj.override = ApiClient.convertToType(data['override'], 'Boolean');
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('creation_time'))
        obj.creationTime = ApiClient.convertToType(data['creation_time'], 'String');
      if (data.hasOwnProperty('update_time'))
        obj.updateTime = ApiClient.convertToType(data['update_time'], 'String');
    }
    return obj;
  }

  /**
   * The policy ID.
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * The policy name.
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * The description of the policy.
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * The source registry.
   * @member {module:model/Registry} srcRegistry
   */
  exports.prototype.srcRegistry = undefined;

  /**
   * The destination registry.
   * @member {module:model/Registry} destRegistry
   */
  exports.prototype.destRegistry = undefined;

  /**
   * The destination namespace.
   * @member {String} destNamespace
   */
  exports.prototype.destNamespace = undefined;

  /**
   * @member {module:model/ReplicationTrigger} trigger
   */
  exports.prototype.trigger = undefined;

  /**
   * The replication policy filter array.
   * @member {Array.<module:model/ReplicationFilter>} filters
   */
  exports.prototype.filters = undefined;

  /**
   * Whether to replicate the deletion operation.
   * @member {Boolean} deletion
   */
  exports.prototype.deletion = undefined;

  /**
   * Whether to override the resources on the destination registry.
   * @member {Boolean} override
   */
  exports.prototype.override = undefined;

  /**
   * Whether the policy is enabled or not.
   * @member {Boolean} enabled
   */
  exports.prototype.enabled = undefined;

  /**
   * The create time of the policy.
   * @member {String} creationTime
   */
  exports.prototype.creationTime = undefined;

  /**
   * The update time of the policy.
   * @member {String} updateTime
   */
  exports.prototype.updateTime = undefined;


  return exports;

}));
