/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RetentionRuleParamMetadata'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RetentionRuleParamMetadata'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.RetentionRuleMetadata = factory(root.HarborApi.ApiClient, root.HarborApi.RetentionRuleParamMetadata);
  }
}(this, function(ApiClient, RetentionRuleParamMetadata) {
  'use strict';

  /**
   * The RetentionRuleMetadata model module.
   * @module model/RetentionRuleMetadata
   * @version 2.0
   */

  /**
   * Constructs a new <code>RetentionRuleMetadata</code>.
   * the tag retention rule metadata
   * @alias module:model/RetentionRuleMetadata
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RetentionRuleMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RetentionRuleMetadata} obj Optional instance to populate.
   * @return {module:model/RetentionRuleMetadata} The populated <code>RetentionRuleMetadata</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('rule_template'))
        obj.ruleTemplate = ApiClient.convertToType(data['rule_template'], 'String');
      if (data.hasOwnProperty('display_text'))
        obj.displayText = ApiClient.convertToType(data['display_text'], 'String');
      if (data.hasOwnProperty('action'))
        obj.action = ApiClient.convertToType(data['action'], 'String');
      if (data.hasOwnProperty('params'))
        obj.params = ApiClient.convertToType(data['params'], [RetentionRuleParamMetadata]);
    }
    return obj;
  }

  /**
   * rule id
   * @member {String} ruleTemplate
   */
  exports.prototype.ruleTemplate = undefined;

  /**
   * rule display text
   * @member {String} displayText
   */
  exports.prototype.displayText = undefined;

  /**
   * rule action
   * @member {String} action
   */
  exports.prototype.action = undefined;

  /**
   * rule params
   * @member {Array.<module:model/RetentionRuleParamMetadata>} params
   */
  exports.prototype.params = undefined;


  return exports;

}));
