/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.RetentionExecution = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RetentionExecution model module.
   * @module model/RetentionExecution
   * @version 2.0
   */

  /**
   * Constructs a new <code>RetentionExecution</code>.
   * @alias module:model/RetentionExecution
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RetentionExecution</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RetentionExecution} obj Optional instance to populate.
   * @return {module:model/RetentionExecution} The populated <code>RetentionExecution</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('policy_id'))
        obj.policyId = ApiClient.convertToType(data['policy_id'], 'Number');
      if (data.hasOwnProperty('start_time'))
        obj.startTime = ApiClient.convertToType(data['start_time'], 'String');
      if (data.hasOwnProperty('end_time'))
        obj.endTime = ApiClient.convertToType(data['end_time'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('trigger'))
        obj.trigger = ApiClient.convertToType(data['trigger'], 'String');
      if (data.hasOwnProperty('dry_run'))
        obj.dryRun = ApiClient.convertToType(data['dry_run'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Number} policyId
   */
  exports.prototype.policyId = undefined;

  /**
   * @member {String} startTime
   */
  exports.prototype.startTime = undefined;

  /**
   * @member {String} endTime
   */
  exports.prototype.endTime = undefined;

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} trigger
   */
  exports.prototype.trigger = undefined;

  /**
   * @member {Boolean} dryRun
   */
  exports.prototype.dryRun = undefined;


  return exports;

}));
