/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RetentionPolicyScope', 'model/RetentionRule', 'model/RetentionRuleTrigger'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RetentionPolicyScope'), require('./RetentionRule'), require('./RetentionRuleTrigger'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.RetentionPolicy = factory(root.HarborApi.ApiClient, root.HarborApi.RetentionPolicyScope, root.HarborApi.RetentionRule, root.HarborApi.RetentionRuleTrigger);
  }
}(this, function(ApiClient, RetentionPolicyScope, RetentionRule, RetentionRuleTrigger) {
  'use strict';

  /**
   * The RetentionPolicy model module.
   * @module model/RetentionPolicy
   * @version 2.0
   */

  /**
   * Constructs a new <code>RetentionPolicy</code>.
   * retention policy
   * @alias module:model/RetentionPolicy
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RetentionPolicy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RetentionPolicy} obj Optional instance to populate.
   * @return {module:model/RetentionPolicy} The populated <code>RetentionPolicy</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('algorithm'))
        obj.algorithm = ApiClient.convertToType(data['algorithm'], 'String');
      if (data.hasOwnProperty('rules'))
        obj.rules = ApiClient.convertToType(data['rules'], [RetentionRule]);
      if (data.hasOwnProperty('trigger'))
        obj.trigger = RetentionRuleTrigger.constructFromObject(data['trigger']);
      if (data.hasOwnProperty('scope'))
        obj.scope = RetentionPolicyScope.constructFromObject(data['scope']);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} algorithm
   */
  exports.prototype.algorithm = undefined;

  /**
   * @member {Array.<module:model/RetentionRule>} rules
   */
  exports.prototype.rules = undefined;

  /**
   * @member {module:model/RetentionRuleTrigger} trigger
   */
  exports.prototype.trigger = undefined;

  /**
   * @member {module:model/RetentionPolicyScope} scope
   */
  exports.prototype.scope = undefined;


  return exports;

}));
