/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RetentionRuleMetadata', 'model/RetentionSelectorMetadata'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RetentionRuleMetadata'), require('./RetentionSelectorMetadata'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.RetentionMetadata = factory(root.HarborApi.ApiClient, root.HarborApi.RetentionRuleMetadata, root.HarborApi.RetentionSelectorMetadata);
  }
}(this, function(ApiClient, RetentionRuleMetadata, RetentionSelectorMetadata) {
  'use strict';

  /**
   * The RetentionMetadata model module.
   * @module model/RetentionMetadata
   * @version 2.0
   */

  /**
   * Constructs a new <code>RetentionMetadata</code>.
   * the tag retention metadata
   * @alias module:model/RetentionMetadata
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RetentionMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RetentionMetadata} obj Optional instance to populate.
   * @return {module:model/RetentionMetadata} The populated <code>RetentionMetadata</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('templates'))
        obj.templates = ApiClient.convertToType(data['templates'], [RetentionRuleMetadata]);
      if (data.hasOwnProperty('scope_selectors'))
        obj.scopeSelectors = ApiClient.convertToType(data['scope_selectors'], [RetentionSelectorMetadata]);
      if (data.hasOwnProperty('tag_selectors'))
        obj.tagSelectors = ApiClient.convertToType(data['tag_selectors'], [RetentionSelectorMetadata]);
    }
    return obj;
  }

  /**
   * templates
   * @member {Array.<module:model/RetentionRuleMetadata>} templates
   */
  exports.prototype.templates = undefined;

  /**
   * supported scope selectors
   * @member {Array.<module:model/RetentionSelectorMetadata>} scopeSelectors
   */
  exports.prototype.scopeSelectors = undefined;

  /**
   * supported tag selectors
   * @member {Array.<module:model/RetentionSelectorMetadata>} tagSelectors
   */
  exports.prototype.tagSelectors = undefined;


  return exports;

}));
