/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RobotPermission'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RobotPermission'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.RobotCreate = factory(root.HarborApi.ApiClient, root.HarborApi.RobotPermission);
  }
}(this, function(ApiClient, RobotPermission) {
  'use strict';

  /**
   * The RobotCreate model module.
   * @module model/RobotCreate
   * @version 2.0
   */

  /**
   * Constructs a new <code>RobotCreate</code>.
   * The request for robot account creation.
   * @alias module:model/RobotCreate
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RobotCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RobotCreate} obj Optional instance to populate.
   * @return {module:model/RobotCreate} The populated <code>RobotCreate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('secret'))
        obj.secret = ApiClient.convertToType(data['secret'], 'String');
      if (data.hasOwnProperty('level'))
        obj.level = ApiClient.convertToType(data['level'], 'String');
      if (data.hasOwnProperty('disable'))
        obj.disable = ApiClient.convertToType(data['disable'], 'Boolean');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'Number');
      if (data.hasOwnProperty('permissions'))
        obj.permissions = ApiClient.convertToType(data['permissions'], [RobotPermission]);
    }
    return obj;
  }

  /**
   * The name of the tag
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * The description of the robot
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * The secret of the robot
   * @member {String} secret
   */
  exports.prototype.secret = undefined;

  /**
   * The level of the robot, project or system
   * @member {String} level
   */
  exports.prototype.level = undefined;

  /**
   * The disable status of the robot
   * @member {Boolean} disable
   */
  exports.prototype.disable = undefined;

  /**
   * The duration of the robot in days
   * @member {Number} duration
   */
  exports.prototype.duration = undefined;

  /**
   * @member {Array.<module:model/RobotPermission>} permissions
   */
  exports.prototype.permissions = undefined;


  return exports;

}));
