/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.Role = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Role model module.
   * @module model/Role
   * @version 2.0
   */

  /**
   * Constructs a new <code>Role</code>.
   * @alias module:model/Role
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Role</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Role} obj Optional instance to populate.
   * @return {module:model/Role} The populated <code>Role</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('role_id'))
        obj.roleId = ApiClient.convertToType(data['role_id'], 'Number');
      if (data.hasOwnProperty('role_code'))
        obj.roleCode = ApiClient.convertToType(data['role_code'], 'String');
      if (data.hasOwnProperty('role_name'))
        obj.roleName = ApiClient.convertToType(data['role_name'], 'String');
      if (data.hasOwnProperty('role_mask'))
        obj.roleMask = ApiClient.convertToType(data['role_mask'], 'String');
    }
    return obj;
  }

  /**
   * ID in table.
   * @member {Number} roleId
   */
  exports.prototype.roleId = undefined;

  /**
   * Description of permissions for the role.
   * @member {String} roleCode
   */
  exports.prototype.roleCode = undefined;

  /**
   * Name the the role.
   * @member {String} roleName
   */
  exports.prototype.roleName = undefined;

  /**
   * @member {String} roleMask
   */
  exports.prototype.roleMask = undefined;


  return exports;

}));
