/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.ScheduleObj = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ScheduleObj model module.
   * @module model/ScheduleObj
   * @version 2.0
   */

  /**
   * Constructs a new <code>ScheduleObj</code>.
   * @alias module:model/ScheduleObj
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ScheduleObj</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScheduleObj} obj Optional instance to populate.
   * @return {module:model/ScheduleObj} The populated <code>ScheduleObj</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('cron'))
        obj.cron = ApiClient.convertToType(data['cron'], 'String');
    }
    return obj;
  }

  /**
   * The schedule type. The valid values are 'Hourly', 'Daily', 'Weekly', 'Custom', 'Manual' and 'None'. 'Manual' means to trigger it right away and 'None' means to cancel the schedule. 
   * @member {module:model/ScheduleObj.TypeEnum} type
   */
  exports.prototype.type = undefined;

  /**
   * A cron expression, a time-based job scheduler.
   * @member {String} cron
   */
  exports.prototype.cron = undefined;



  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "Hourly"
     * @const
     */
    hourly: "Hourly",

    /**
     * value: "Daily"
     * @const
     */
    daily: "Daily",

    /**
     * value: "Weekly"
     * @const
     */
    weekly: "Weekly",

    /**
     * value: "Custom"
     * @const
     */
    custom: "Custom",

    /**
     * value: "Manual"
     * @const
     */
    manual: "Manual",

    /**
     * value: "None"
     * @const
     */
    none: "None"
  };

  return exports;

}));
