/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ScheduleObj'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ScheduleObj'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.Schedule = factory(root.HarborApi.ApiClient, root.HarborApi.ScheduleObj);
  }
}(this, function(ApiClient, ScheduleObj) {
  'use strict';

  /**
   * The Schedule model module.
   * @module model/Schedule
   * @version 2.0
   */

  /**
   * Constructs a new <code>Schedule</code>.
   * @alias module:model/Schedule
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Schedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Schedule} obj Optional instance to populate.
   * @return {module:model/Schedule} The populated <code>Schedule</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('creation_time'))
        obj.creationTime = ApiClient.convertToType(data['creation_time'], 'Date');
      if (data.hasOwnProperty('update_time'))
        obj.updateTime = ApiClient.convertToType(data['update_time'], 'Date');
      if (data.hasOwnProperty('schedule'))
        obj.schedule = ScheduleObj.constructFromObject(data['schedule']);
      if (data.hasOwnProperty('parameters'))
        obj.parameters = ApiClient.convertToType(data['parameters'], {'String': Object});
    }
    return obj;
  }

  /**
   * The id of the schedule.
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * The status of the schedule.
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * the creation time of the schedule.
   * @member {Date} creationTime
   */
  exports.prototype.creationTime = undefined;

  /**
   * the update time of the schedule.
   * @member {Date} updateTime
   */
  exports.prototype.updateTime = undefined;

  /**
   * @member {module:model/ScheduleObj} schedule
   */
  exports.prototype.schedule = undefined;

  /**
   * The parameters of schedule job
   * @member {Object.<String, Object>} parameters
   */
  exports.prototype.parameters = undefined;


  return exports;

}));
