/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Project', 'model/SearchRepository', 'model/SearchResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Project'), require('./SearchRepository'), require('./SearchResult'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.Search = factory(root.HarborApi.ApiClient, root.HarborApi.Project, root.HarborApi.SearchRepository, root.HarborApi.SearchResult);
  }
}(this, function(ApiClient, Project, SearchRepository, SearchResult) {
  'use strict';

  /**
   * The Search model module.
   * @module model/Search
   * @version 2.0
   */

  /**
   * Constructs a new <code>Search</code>.
   * @alias module:model/Search
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Search</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Search} obj Optional instance to populate.
   * @return {module:model/Search} The populated <code>Search</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('project'))
        obj.project = ApiClient.convertToType(data['project'], [Project]);
      if (data.hasOwnProperty('repository'))
        obj.repository = ApiClient.convertToType(data['repository'], [SearchRepository]);
      if (data.hasOwnProperty('chart'))
        obj.chart = ApiClient.convertToType(data['chart'], [SearchResult]);
    }
    return obj;
  }

  /**
   * Search results of the projects that matched the filter keywords.
   * @member {Array.<module:model/Project>} project
   */
  exports.prototype.project = undefined;

  /**
   * Search results of the repositories that matched the filter keywords.
   * @member {Array.<module:model/SearchRepository>} repository
   */
  exports.prototype.repository = undefined;

  /**
   * Search results of the charts that macthed the filter keywords.
   * @member {Array.<module:model/SearchResult>} chart
   */
  exports.prototype.chart = undefined;


  return exports;

}));
