/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.StringConfigItem = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The StringConfigItem model module.
   * @module model/StringConfigItem
   * @version 2.0
   */

  /**
   * Constructs a new <code>StringConfigItem</code>.
   * @alias module:model/StringConfigItem
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>StringConfigItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StringConfigItem} obj Optional instance to populate.
   * @return {module:model/StringConfigItem} The populated <code>StringConfigItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('editable'))
        obj.editable = ApiClient.convertToType(data['editable'], 'Boolean');
    }
    return obj;
  }

  /**
   * The string value of current config item
   * @member {String} value
   */
  exports.prototype.value = undefined;

  /**
   * The configure item can be updated or not
   * @member {Boolean} editable
   */
  exports.prototype.editable = undefined;


  return exports;

}));
