/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EventType', 'model/NotifyType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EventType'), require('./NotifyType'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.SupportedWebhookEventTypes = factory(root.HarborApi.ApiClient, root.HarborApi.EventType, root.HarborApi.NotifyType);
  }
}(this, function(ApiClient, EventType, NotifyType) {
  'use strict';

  /**
   * The SupportedWebhookEventTypes model module.
   * @module model/SupportedWebhookEventTypes
   * @version 2.0
   */

  /**
   * Constructs a new <code>SupportedWebhookEventTypes</code>.
   * Supportted webhook event types and notify types.
   * @alias module:model/SupportedWebhookEventTypes
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SupportedWebhookEventTypes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SupportedWebhookEventTypes} obj Optional instance to populate.
   * @return {module:model/SupportedWebhookEventTypes} The populated <code>SupportedWebhookEventTypes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('event_type'))
        obj.eventType = ApiClient.convertToType(data['event_type'], [EventType]);
      if (data.hasOwnProperty('notify_type'))
        obj.notifyType = ApiClient.convertToType(data['notify_type'], [NotifyType]);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/EventType>} eventType
   */
  exports.prototype.eventType = undefined;

  /**
   * @member {Array.<module:model/NotifyType>} notifyType
   */
  exports.prototype.notifyType = undefined;


  return exports;

}));
