/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.Tag = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Tag model module.
   * @module model/Tag
   * @version 2.0
   */

  /**
   * Constructs a new <code>Tag</code>.
   * @alias module:model/Tag
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Tag</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tag} obj Optional instance to populate.
   * @return {module:model/Tag} The populated <code>Tag</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('repository_id'))
        obj.repositoryId = ApiClient.convertToType(data['repository_id'], 'Number');
      if (data.hasOwnProperty('artifact_id'))
        obj.artifactId = ApiClient.convertToType(data['artifact_id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('push_time'))
        obj.pushTime = ApiClient.convertToType(data['push_time'], 'Date');
      if (data.hasOwnProperty('pull_time'))
        obj.pullTime = ApiClient.convertToType(data['pull_time'], 'Date');
      if (data.hasOwnProperty('immutable'))
        obj.immutable = ApiClient.convertToType(data['immutable'], 'Boolean');
      if (data.hasOwnProperty('signed'))
        obj.signed = ApiClient.convertToType(data['signed'], 'Boolean');
    }
    return obj;
  }

  /**
   * The ID of the tag
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * The ID of the repository that the tag belongs to
   * @member {Number} repositoryId
   */
  exports.prototype.repositoryId = undefined;

  /**
   * The ID of the artifact that the tag attached to
   * @member {Number} artifactId
   */
  exports.prototype.artifactId = undefined;

  /**
   * The name of the tag
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * The push time of the tag
   * @member {Date} pushTime
   */
  exports.prototype.pushTime = undefined;

  /**
   * The latest pull time of the tag
   * @member {Date} pullTime
   */
  exports.prototype.pullTime = undefined;

  /**
   * The immutable status of the tag
   * @member {Boolean} immutable
   */
  exports.prototype.immutable = undefined;

  /**
   * The attribute indicates whether the tag is signed or not
   * @member {Boolean} signed
   */
  exports.prototype.signed = undefined;


  return exports;

}));
