/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.UserGroup = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UserGroup model module.
   * @module model/UserGroup
   * @version 2.0
   */

  /**
   * Constructs a new <code>UserGroup</code>.
   * @alias module:model/UserGroup
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UserGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserGroup} obj Optional instance to populate.
   * @return {module:model/UserGroup} The populated <code>UserGroup</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('group_name'))
        obj.groupName = ApiClient.convertToType(data['group_name'], 'String');
      if (data.hasOwnProperty('group_type'))
        obj.groupType = ApiClient.convertToType(data['group_type'], 'Number');
      if (data.hasOwnProperty('ldap_group_dn'))
        obj.ldapGroupDn = ApiClient.convertToType(data['ldap_group_dn'], 'String');
    }
    return obj;
  }

  /**
   * The ID of the user group
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * The name of the user group
   * @member {String} groupName
   */
  exports.prototype.groupName = undefined;

  /**
   * The group type, 1 for LDAP group, 2 for HTTP group.
   * @member {Number} groupType
   */
  exports.prototype.groupType = undefined;

  /**
   * The DN of the LDAP group if group type is 1 (LDAP group).
   * @member {String} ldapGroupDn
   */
  exports.prototype.ldapGroupDn = undefined;


  return exports;

}));
