/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.WebhookJob = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The WebhookJob model module.
   * @module model/WebhookJob
   * @version 2.0
   */

  /**
   * Constructs a new <code>WebhookJob</code>.
   * The webhook job.
   * @alias module:model/WebhookJob
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WebhookJob</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookJob} obj Optional instance to populate.
   * @return {module:model/WebhookJob} The populated <code>WebhookJob</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('policy_id'))
        obj.policyId = ApiClient.convertToType(data['policy_id'], 'Number');
      if (data.hasOwnProperty('event_type'))
        obj.eventType = ApiClient.convertToType(data['event_type'], 'String');
      if (data.hasOwnProperty('notify_type'))
        obj.notifyType = ApiClient.convertToType(data['notify_type'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('job_detail'))
        obj.jobDetail = ApiClient.convertToType(data['job_detail'], 'String');
      if (data.hasOwnProperty('creation_time'))
        obj.creationTime = ApiClient.convertToType(data['creation_time'], 'String');
      if (data.hasOwnProperty('update_time'))
        obj.updateTime = ApiClient.convertToType(data['update_time'], 'String');
    }
    return obj;
  }

  /**
   * The webhook job ID.
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * The webhook policy ID.
   * @member {Number} policyId
   */
  exports.prototype.policyId = undefined;

  /**
   * The webhook job event type.
   * @member {String} eventType
   */
  exports.prototype.eventType = undefined;

  /**
   * The webhook job notify type.
   * @member {String} notifyType
   */
  exports.prototype.notifyType = undefined;

  /**
   * The webhook job status.
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * The webhook job notify detailed data.
   * @member {String} jobDetail
   */
  exports.prototype.jobDetail = undefined;

  /**
   * The webhook job creation time.
   * @member {String} creationTime
   */
  exports.prototype.creationTime = undefined;

  /**
   * The webhook job update time.
   * @member {String} updateTime
   */
  exports.prototype.updateTime = undefined;


  return exports;

}));
