/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.WebhookTargetObject = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The WebhookTargetObject model module.
   * @module model/WebhookTargetObject
   * @version 2.0
   */

  /**
   * Constructs a new <code>WebhookTargetObject</code>.
   * The webhook policy target object.
   * @alias module:model/WebhookTargetObject
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WebhookTargetObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookTargetObject} obj Optional instance to populate.
   * @return {module:model/WebhookTargetObject} The populated <code>WebhookTargetObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('auth_header'))
        obj.authHeader = ApiClient.convertToType(data['auth_header'], 'String');
      if (data.hasOwnProperty('skip_cert_verify'))
        obj.skipCertVerify = ApiClient.convertToType(data['skip_cert_verify'], 'Boolean');
    }
    return obj;
  }

  /**
   * The webhook target notify type.
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * The webhook target address.
   * @member {String} address
   */
  exports.prototype.address = undefined;

  /**
   * The webhook auth header.
   * @member {String} authHeader
   */
  exports.prototype.authHeader = undefined;

  /**
   * Whether or not to skip cert verify.
   * @member {Boolean} skipCertVerify
   */
  exports.prototype.skipCertVerify = undefined;


  return exports;

}));
