/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WebhookTargetObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WebhookTargetObject'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.WebhookPolicy = factory(root.HarborApi.ApiClient, root.HarborApi.WebhookTargetObject);
  }
}(this, function(ApiClient, WebhookTargetObject) {
  'use strict';

  /**
   * The WebhookPolicy model module.
   * @module model/WebhookPolicy
   * @version 2.0
   */

  /**
   * Constructs a new <code>WebhookPolicy</code>.
   * The webhook policy object
   * @alias module:model/WebhookPolicy
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WebhookPolicy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookPolicy} obj Optional instance to populate.
   * @return {module:model/WebhookPolicy} The populated <code>WebhookPolicy</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('project_id'))
        obj.projectId = ApiClient.convertToType(data['project_id'], 'Number');
      if (data.hasOwnProperty('targets'))
        obj.targets = ApiClient.convertToType(data['targets'], [WebhookTargetObject]);
      if (data.hasOwnProperty('event_types'))
        obj.eventTypes = ApiClient.convertToType(data['event_types'], ['String']);
      if (data.hasOwnProperty('creator'))
        obj.creator = ApiClient.convertToType(data['creator'], 'String');
      if (data.hasOwnProperty('creation_time'))
        obj.creationTime = ApiClient.convertToType(data['creation_time'], 'String');
      if (data.hasOwnProperty('update_time'))
        obj.updateTime = ApiClient.convertToType(data['update_time'], 'String');
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
    }
    return obj;
  }

  /**
   * The webhook policy ID.
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * The name of webhook policy.
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * The description of webhook policy.
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * The project ID of webhook policy.
   * @member {Number} projectId
   */
  exports.prototype.projectId = undefined;

  /**
   * @member {Array.<module:model/WebhookTargetObject>} targets
   */
  exports.prototype.targets = undefined;

  /**
   * @member {Array.<String>} eventTypes
   */
  exports.prototype.eventTypes = undefined;

  /**
   * The creator of the webhook policy.
   * @member {String} creator
   */
  exports.prototype.creator = undefined;

  /**
   * The create time of the webhook policy.
   * @member {String} creationTime
   */
  exports.prototype.creationTime = undefined;

  /**
   * The update time of the webhook policy.
   * @member {String} updateTime
   */
  exports.prototype.updateTime = undefined;

  /**
   * Whether the webhook policy is enabled or not.
   * @member {Boolean} enabled
   */
  exports.prototype.enabled = undefined;


  return exports;

}));
