/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarborApi) {
      root.HarborApi = {};
    }
    root.HarborApi.WebhookLastTrigger = factory(root.HarborApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The WebhookLastTrigger model module.
   * @module model/WebhookLastTrigger
   * @version 2.0
   */

  /**
   * Constructs a new <code>WebhookLastTrigger</code>.
   * The webhook policy and last trigger time group by event type.
   * @alias module:model/WebhookLastTrigger
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WebhookLastTrigger</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookLastTrigger} obj Optional instance to populate.
   * @return {module:model/WebhookLastTrigger} The populated <code>WebhookLastTrigger</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('event_type'))
        obj.eventType = ApiClient.convertToType(data['event_type'], 'String');
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('creation_time'))
        obj.creationTime = ApiClient.convertToType(data['creation_time'], 'String');
      if (data.hasOwnProperty('last_trigger_time'))
        obj.lastTriggerTime = ApiClient.convertToType(data['last_trigger_time'], 'String');
    }
    return obj;
  }

  /**
   * The webhook event type.
   * @member {String} eventType
   */
  exports.prototype.eventType = undefined;

  /**
   * Whether or not the webhook policy enabled.
   * @member {Boolean} enabled
   */
  exports.prototype.enabled = undefined;

  /**
   * The creation time of webhook policy.
   * @member {String} creationTime
   */
  exports.prototype.creationTime = undefined;

  /**
   * The last trigger time of webhook policy.
   * @member {String} lastTriggerTime
   */
  exports.prototype.lastTriggerTime = undefined;


  return exports;

}));
