services:

  backend:
    image: ${BACKEND_IMAGE}
    restart: unless-stopped
    container_name: playground-backend
    networks:
      playground-net:
      proxynet:
    volumes:
      - "playground-dindcerts-client:/usr/src/app/dind-certs-client/certs:ro"
    environment:
      KEYCLOAK_REALM: ${PLAYGROUND_KEYCLOAK_REALM}
      KEYCLOAK_SERVER_URL: https://auth.${PROD_SERVICE_DOMAIN}/auth
      KEYCLOAK_CLIENT_ID: playground
      API_PORT: 80
      LOGGER_LEVEL: info
      DOCKER_HOST: playground-dind
      DOCKER_PORT: 2376
      CORS_ORIGIN: https://playground.${SERVICE_DOMAIN}
      METADATA_ENDPOINT: http://blazegraph:9999/bigdata/sparql
      VIRTUAL_HOST: "playgroundapi.${SERVICE_DOMAIN}, www.playgroundapi.${SERVICE_DOMAIN}"
      LETSENCRYPT_HOST: "playgroundapi.${SERVICE_DOMAIN}, www.playgroundapi.${SERVICE_DOMAIN}"
      VIRTUAL_PORT: 80

  frontend: 
    image: ${FRONTEND_IMAGE}
    restart: unless-stopped
    container_name: playground-frontend
    networks:
      proxynet:
    environment:
      VIRTUAL_HOST: "playground.${SERVICE_DOMAIN}, www.playground.${SERVICE_DOMAIN}"
      LETSENCRYPT_HOST: "playground.${SERVICE_DOMAIN}, www.playground.${SERVICE_DOMAIN}"

  dind:
    image: ${DIND_IMAGE}
    container_name: 'playground-dind'
    restart: unless-stopped
    environment:
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_TLS_SAN: DNS:playground-dind
    volumes:
      - "playground-dindcerts-ca:/certs/ca"
      - "playground-dindcerts-client:/certs/client"
    networks:
      playground-net: 
    privileged: true
    # Add the address of menzel as an extra host.
    # Without this configuration, menzel.informatik... will be resolved to 'localhost‘.
    # This will of course not work as intended because this directs to the playground
    # containers themselves
    #TODO: Make configurable
    extra_hosts:
      - "menzel.informatik.rwth-aachen.de:137.226.232.26"
    
  blazegraph:
    image: ${BLAZEGRAPH_IMAGE}
    container_name: 'playground-blaze'
    restart: unless-stopped
    ports: 
      #Accessible via ssh tunnel
      # Other port than the local blazegraph installation because otherwise this might clash (you would accidentally use the local one instead in the tunnel)
      - "127.0.0.1:9998:9999"
    volumes:
      - "playground-blazedata:/workdir/data/"
    networks:
      playground-net: 
        aliases: 
          - blazegraph

networks:
  playground-net:
  proxynet:
    external: true
volumes:
  playground-dindcerts-ca:
  playground-dindcerts-client:
  playground-blazedata: